source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.0.0"

# Specific versions for Xcode 26 compatibility
gem 'cocoapods', '1.14.3'
gem 'activesupport', '7.1.2'
gem 'xcodeproj', '1.24.0'
gem 'concurrent-ruby', '1.2.3'
gem 'ffi', '1.16.3'  # Add explicit ffi version
gem 'json', '2.7.1'  # Add explicit json version